### PR TITLE
Fixes for Chef 15

### PR DESCRIPTION
**Pull request by EMH333**
Straightforward changes except one thing.

I ran into trouble initially completing the integration testing until I set `repo_gpgcheck` to `false` for the `libnvidia-container`, `nvidia-container-runtime`, and `nvidia-docker` repos as it gave this error:

```log
     ================================================================================
     Error executing action `run` on resource 'execute[yum-makecache-nvidia-docker]'
     ================================================================================
     
     Mixlib::ShellOut::ShellCommandFailed
     ------------------------------------
     Expected process to exit with [0], but received ''
     ---- Begin output of yum -q -y makecache --disablerepo=* --enablerepo=nvidia-docker ----
     STDOUT: 
     STDERR: Importing GPG key 0xF796ECB0:
Userid     : "NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>"
Fingerprint: C95B 321B 61E8 8C18 09C4 F759 DDCA E044 F796 ECB0
From       : https://nvidia.github.io/nvidia-docker/gpgkey
     ---- End output of yum -q -y makecache --disablerepo=* --enablerepo=nvidia-docker ----
     Ran yum -q -y makecache --disablerepo=* --enablerepo=nvidia-docker returned 
     
     Resource Declaration:
     ---------------------
     # In /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.15.6/lib/chef/provider/yum_repository.rb
     
60:         declare_resource(:execute, "yum-makecache-#{new_resource.repositoryid}") do
61:           command "yum -q -y makecache --disablerepo=* --enablerepo=#{new_resource.repositoryid}"
62:           action :nothing
63:           only_if { new_resource.enabled }
64:         end
65: 
     
     Compiled Resource:
     ------------------
     # Declared in /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.15.6/lib/chef/provider/yum_repository.rb:60:in `block in <class:YumRepository>'
     
     execute("yum-makecache-nvidia-docker") do
action [:nothing]
default_guard_interpreter :execute
command "yum -q -y makecache --disablerepo=* --enablerepo=nvidia-docker"
backup 5
declared_type :execute
cookbook_name "yum-nvidia"
domain nil
user nil
only_if { #code block }
     end
     
     System Info:
     ------------
     chef_version=14.15.6
     platform=centos
     platform_version=8.1.1911
     ruby=ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
     program_name=/opt/chef/bin/chef-solo
     executable=/opt/chef/bin/chef-solo
```

I didn't include that change in this PR as I wasn't sure if that would be acceptable. I also ran the command that was giving the problem in the VM and it finished with no issues so it's rather weird to me that it would error like this

### CODE REVIEW

**Comment by EMH333** [comment]
https://github.com/chef-cookbooks/yum/issues/124 was the closest issue I could find to the problem I'm running into

**Comment by ramereth** [comment]
@EMH333 this is working for me now, can you please try again and let me know if you still have an issue with this?

**Comment by EMH333** [comment]
@ramereth The centos 7 build works no problem, the centos 8 build still has that same error for me

**Comment by ramereth** [comment]
[Chef 15: yum-nvidia](https://trello.com/c/vzeC4laa/1822-chef-15-yum-nvidia)

**Review by ramereth — APPROVED** [review]
This magically works for me now. Please do a minor bump on ``*`` envs.

**Comment by EMH333** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.2.0.  Have a nice day!

**Pull request merged**
